[project]
name = "aino"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.2.0",
    "numpy>=2.4.2",
    "scikit-learn>=1.8.0",
]
